name: ecommerce_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.3.4

dependencies:
  auto_size_text: null
  bloc: ^9.0.0
  cached_network_image: null
  carousel_slider_plus: null
  colornames: null
  connectivity_plus: ^6.1.4
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_native_splash: null
  flutter_screenutil: null
  flutter_slidable: null
  flutter_svg: null
  readmore: null
  shared_preferences: ^2.5.2
  smooth_page_indicator: null
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_lints: null
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/svg_images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-.ttf
